version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        restart: unless-stopped

    web:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: unless-stopped

    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: appoint
            MYSQL_USER: appoint_user
            MYSQL_PASSWORD: appoint_password
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        depends_on:
            - db
        restart: unless-stopped

volumes:
    db_data:
